export const routes = {
  home: '/',
  login: '/login',
  register: '/register',
  terms: '/terms',
  privacy: '/privacy',
  cookies: '/cookies',
  faq: '/faq',
  onboarding: '/onboarding',
  dashboard: '/dashboard',
  assets: '/assets',
  asset: (assetId: number | string) => `/assets/${assetId}`,
  scans: '/scans',
  scan: (scanId: number | string) => `/scans/${scanId}`,
  findings: '/findings',
  finding: (findingId: number | string) => `/findings/${findingId}`,
  reports: '/reports',
  mitre: '/mitre',
  osint: '/osint',
  settings: '/settings',
} as const;
